# Generated by Django 4.2.3 on 2023-08-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=7, verbose_name="ZIP/Postal code"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.country",
            ),
        ),
    ]
