# Generated by Django 4.2.3 on 2023-08-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0002_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sort',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products_catalogue.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
