# Generated by Django 4.2.3 on 2023-08-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_catalogue", "0005_alter_category_name_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]