# Generated by Django 4.2.3 on 2023-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0007_product_alter_category_slug_productimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_last_30_days',
            new_name='lowest_price_last_30_days',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]