# Generated by Django 4.2.4 on 2023-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0008_rename_price_last_30_days_product_lowest_price_last_30_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeneoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
