# Generated by Django 4.2.4 on 2023-08-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0009_ceneocategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceneocategory',
            options={'verbose_name': 'CeneoCategory', 'verbose_name_plural': 'CeneoCategories'},
        ),
        migrations.AddField(
            model_name='category',
            name='ceneo_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_catalogue.ceneocategory'),
        ),
    ]
