# Generated by Django 4.2.3 on 2023-08-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0010_alter_ceneocategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ceneo_category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='ceneo_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_catalogue.ceneocategory'),
        ),
    ]
