# Generated by Django 4.2.6 on 2023-10-24 09:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0011_remove_category_ceneo_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
