# Generated by Django 4.2.5 on 2023-10-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products_catalogue", "0011_remove_category_ceneo_category_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_change_history",
                        to="products_catalogue.product",
                    ),
                ),
            ],
        ),
    ]
