# Generated by Django 4.2.6 on 2023-11-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0012_alter_product_full_description_and_more'),
        ('products_catalogue', '0012_category_updated_at'),
    ]

    operations = [
    ]
