# Generated by Django 4.2.6 on 2023-10-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0012_alter_product_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceneocategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_catalogue.ceneocategory'),
        ),
    ]
