# Generated by Django 4.2.6 on 2023-11-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products_catalogue", "0013_pricechangehistory_disabled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="lowest_price_last_30_days",
        ),
    ]
