# Generated by Django 4.2.6 on 2023-10-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0013_ceneocategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dostępny, sklep wyśle produkt w ciągu 24 godzin'), (3, 'Sklep wyśle produkt do 3 dni'), (7, 'Sklep wyśle produkt w ciągu tygodnia'), (14, 'Sklep wyśle produkt do 14 dni'), (90, 'Towar na zamówienie'), (99, 'Brak informacji o dostępności - status „sprawdź w sklepie”'), (110, 'Przedsprzedaż')], default=1),
        ),
    ]
