# Generated by Django 4.2.6 on 2023-11-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0013_merge_20231104_1200'),
        ('products_catalogue', '0015_alter_product_availability'),
    ]

    operations = [
    ]
