# Generated by Django 4.2.7 on 2023-11-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_catalogue', '0014_remove_product_lowest_price_last_30_days'),
        ('products_catalogue', '0016_merge_20231104_2020'),
    ]

    operations = [
    ]
