# Generated by Django 4.2.7 on 2024-01-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products_catalogue", "0021_auto_20231216_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
