# Generated by Django 4.2.7 on 2024-02-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_catalogue', '0022_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart_details', models.JSONField(default=dict, editable=False)),
                ('cart_total', models.DecimalField(decimal_places=2, default=None, editable=False, max_digits=10)),
                ('delivery_name', models.CharField(editable=False, max_length=255)),
                ('delivery_price', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('total_sum', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products_catalogue.deliverymethod')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
